import {THREE,box,cylinder,ease} from '../engine/runtime.js';
const COLORS={VESPER:['#526c67','#1e2927',0x9ffff1],ROOK:['#6a5544','#241b16',0xffa65e],NIX:['#4f5364','#1c1c25',0xd58cff]};
export class Automaton{
 constructor(name,tex,scale=1){this.name=name;this.root=new THREE.Group();this.root.scale.setScalar(scale);this.root.userData.agent=name;const [base,accent,glow]=COLORS[name],shell=tex.material(base,accent,{metalness:.68,roughness:.36}),joint=tex.material('#252a29','#080a0a',{metalness:.9,roughness:.25});this.parts={};
 const pelvis=this.add(box(.8,.45,.45,shell),0,1.2,0);const torso=this.add(box(1,1.25,.58,shell),0,2,0);torso.rotation.z=name==='NIX'?.08:0;const neck=this.add(cylinder(.18,.28,joint),0,2.76,0);const head=this.parts.head=this.add(box(.78,.67,.68,shell),0,3.15,0);this.parts.jaw=this.add(box(.65,.18,.58,joint),0,2.88,-.08);this.parts.jaw.userData.base=2.88;
 for(const s of[-1,1]){const eyeMat=new THREE.MeshStandardMaterial({color:glow,emissive:glow,emissiveIntensity:5,roughness:.15});const eye=this.add(new THREE.Mesh(new THREE.SphereGeometry(.075,12,8),eyeMat),s*.19,3.2,.35);this.parts['eye'+s]=eye;const arm=this.parts['arm'+s]=new THREE.Group();arm.position.set(s*.67,2.35,0);this.root.add(arm);const upper=cylinder(.13,.72,joint);upper.position.y=-.32;arm.add(upper);const fore=this.parts['fore'+s]=new THREE.Group();fore.position.y=-.72;arm.add(fore);const fm=cylinder(.11,.66,shell);fm.position.y=-.28;fore.add(fm);const hand=box(.25,.22,.23,joint);hand.position.y=-.67;fore.add(hand);for(let f=-1;f<=1;f++){const finger=cylinder(.025,.25,joint,6);finger.position.set(f*.07,-.18,.04);finger.rotation.z=.16*f;hand.add(finger)}const leg=this.parts['leg'+s]=new THREE.Group();leg.position.set(s*.3,1.05,0);this.root.add(leg);const thigh=cylinder(.16,.75,shell);thigh.position.y=-.35;leg.add(thigh);const shin=cylinder(.14,.8,joint);shin.position.y=-1.05;leg.add(shin);const foot=box(.34,.18,.55,shell);foot.position.set(0,-1.48,.13);leg.add(foot)}
 if(name==='VESPER'){for(const s of[-1,1]){const wing=new THREE.Mesh(new THREE.CapsuleGeometry(.3,1,5,10),new THREE.MeshStandardMaterial({color:0x76978e,transparent:true,opacity:.42,side:THREE.DoubleSide,roughness:.6}));wing.scale.set(.8,1.2,.08);wing.position.set(s*.7,2.1,.15);wing.rotation.z=s*.55;this.root.add(wing);this.parts['wing'+s]=wing;const ant=cylinder(.025,.8,joint,6);ant.position.set(s*.2,3.68,0);ant.rotation.z=s*.32;this.root.add(ant)}}
 if(name==='ROOK'){const crest=box(.35,.55,.45,shell);crest.position.set(0,3.65,-.05);crest.rotation.z=.45;this.root.add(crest);for(const s of[-1,1]){const guard=box(.35,.35,.5,shell);guard.position.set(s*.66,2.48,0);this.root.add(guard)}}
 if(name==='NIX'){for(const s of[-1,1])for(let k=0;k<2;k++){const cable=cylinder(.05,1.4,joint,7);cable.position.set(s*(.7+k*.22),1.25,.05);cable.rotation.z=s*(.75+k*.18);this.root.add(cable)}}
 this.root.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true}});this.mode='idle';this.phase=Math.random()*6;this.visible=true}
 add(o,x,y,z){o.position.set(x,y,z);this.root.add(o);return o}
 setMode(m){this.mode=m}
 animate(dt,t,focus){this.phase+=dt*(this.mode==='run'?8:this.mode==='walk'?4:1.2);const p=this.phase,amp=this.mode==='idle'?.04:this.mode==='attack'?1.05:.42;this.parts.head.rotation.y=ease(this.parts.head.rotation.y,focus??Math.sin(p*.4)*.18,dt*4);this.parts.jaw.position.y=this.parts.jaw.userData.base-Math.max(0,Math.sin(p*(this.mode==='attack'?7:1.3)))*(.04+(this.mode==='attack'?.28:0));for(const s of[-1,1]){this.parts['arm'+s].rotation.x=Math.sin(p)*amp*s;this.parts['fore'+s].rotation.x=-.25-Math.max(0,Math.sin(p*s))*.45;this.parts['leg'+s].rotation.x=Math.sin(p)*amp*-s}if(this.name==='VESPER')for(const s of[-1,1])this.parts['wing'+s].rotation.y=Math.sin(p*2)*.24*s;this.root.position.y=Math.sin(p*.5)*.025}
}
export const createRoster=(scene,tex)=>{const roster=[new Automaton('VESPER',tex,.92),new Automaton('ROOK',tex,1.12),new Automaton('NIX',tex,.82)];roster.forEach(a=>scene.add(a.root));return roster};