import {THREE} from '../engine/runtime.js';
const NODES={stage:[0,0,-15],west:[-7,0,-9],east:[7,0,-9],archive:[-8,0,-1],coolant:[8,0,-1],vent:[0,0,-5],left:[-4.6,0,3.7],right:[4.6,0,3.7],office:[0,0,3]};
const PATHS={VESPER:['stage','west','archive','left','office'],ROOK:['stage','east','coolant','right','office'],NIX:['stage','vent','archive','coolant','vent','office']};
export class AgentBrain{
 constructor(body,index){this.body=body;this.name=body.name;this.path=PATHS[this.name];this.index=0;this.state='DORMANT';this.timer=6+Math.random()*7;this.wait=0;this.speed=[1.0,.72,1.32][index];this.aggression=1;this.target=new THREE.Vector3(...NODES.stage);this.body.root.position.copy(this.target);this.body.root.rotation.y=Math.PI}
 reset(night){this.index=0;this.state='WAITING';this.timer=8+Math.random()*7;this.aggression=1+(night-1)*.18;this.body.root.position.set(...NODES.stage);this.body.root.visible=true}
 update(dt,ctx){this.timer-=dt;if(ctx.outage)this.aggression+=dt*.05;if(this.state==='WAITING'){this.body.setMode('idle');if(this.timer<=0)this.decide(ctx)}else if(this.state==='MOVING'){this.body.setMode(this.speed*this.aggression>1.35?'run':'walk');const d=this.target.clone().sub(this.body.root.position),len=d.length();if(len<.12){this.body.root.position.copy(this.target);this.arrive(ctx)}else{d.normalize();this.body.root.position.addScaledVector(d,dt*this.speed*this.aggression);this.body.root.rotation.y=Math.atan2(d.x,d.z)}}else if(this.state==='AT_DOOR'){this.body.setMode('idle');const side=this.name==='ROOK'?'right':this.name==='VESPER'?'left':(Math.random()>.5?'right':'left');if(ctx.lights[side]){this.timer-=dt*1.8}if(ctx.doors[side]){if(this.timer<=0){this.retreat();ctx.event('retreat',this)}}else if(this.timer<=0){this.state='ATTACK';this.timer=this.name==='NIX'?.7:1.6;ctx.event('breach',this)}}else if(this.state==='ATTACK'){this.body.setMode('attack');if(this.timer<=0)ctx.kill(this)}this.body.animate(dt,ctx.time,0)}
 decide(ctx){let chance=.34*this.aggression;if(this.name==='VESPER'&&ctx.tablet)chance*=.55;if(this.name==='ROOK'&&ctx.usage>=4)chance*=1.55;if(this.name==='NIX'&&ctx.camera===5)chance*=.45;if(Math.random()<chance){this.index=Math.min(this.index+1,this.path.length-1);this.target.set(...NODES[this.path[this.index]]);this.state='MOVING';ctx.event('move',this)}else{this.timer=2+Math.random()*4}}
 arrive(ctx){const node=this.path[this.index];if(node==='office'||node==='left'||node==='right'){this.state='AT_DOOR';this.timer=2.4+Math.random()*2.8}else{this.state='WAITING';this.timer=(3+Math.random()*7)/this.aggression;if(Math.random()<.1&&this.name==='NIX')ctx.damageCamera(Math.floor(Math.random()*8))}}
 retreat(){this.index=Math.max(1,this.index-2);this.target.set(...NODES[this.path[this.index]]);this.state='MOVING';this.timer=5}
}
export class AIDirector{constructor(roster){this.brains=roster.map((a,i)=>new AgentBrain(a,i));this.acc=0}reset(n){this.brains.forEach(b=>b.reset(n))}update(dt,ctx){this.acc+=dt;if(this.acc<1/30)return;const step=this.acc;this.acc=0;for(const b of this.brains)b.update(step,ctx)}}