import {RendererRuntime,TextureFactory,THREE} from '../engine/runtime.js';import {Facility} from '../world/facility.js';import {createRoster} from '../entities/automaton.js';import {AIDirector} from '../ai/director.js';import {AudioSystem} from '../systems/audio.js';import {Input} from '../systems/input.js';import {Surveillance,PowerGrid} from '../systems/surveillance.js';import {Interface} from '../ui/interface.js';
export class Game{
 constructor(){this.ui=new Interface();this.audio=new AudioSystem();this.input=new Input();this.rt=new RendererRuntime(document.querySelector('#game'));this.tex=new TextureFactory();this.facility=new Facility(this.rt.scene,this.tex);this.roster=createRoster(this.rt.scene,this.tex);this.ai=new AIDirector(this.roster);this.surveillance=new Surveillance(this.rt.camera,this.ui,this.audio);this.power=new PowerGrid();this.state='menu';this.night=Math.max(1,Math.min(5,Number(localStorage.getItem('np-night')||1)));this.elapsed=0;this.duration=300;this.yaw=0;this.outageTimer=0;this.stepTimer=0;this.bind();this.rt.add((dt,t)=>this.update(dt,t));this.rt.start();setTimeout(()=>this.ui.loaded(),1700)}
 bind(){const q=s=>document.querySelector(s);q('#start').onclick=()=>this.start(this.night);q('#continue').onclick=()=>this.start(this.night);q('#resume').onclick=()=>this.pause(false);q('#restart').onclick=()=>this.start(this.night);q('#quit').onclick=()=>this.title();q('#ending-retry').onclick=()=>this.start(this.night);q('#next-night').onclick=()=>this.start(Math.min(5,this.night+1));q('#tablet-toggle').onclick=()=>this.toggleTablet();document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const [side,type]=b.dataset.action.split('-');type==='door'?this.toggleDoor(side):this.toggleLight(side)})}
 start(night){this.audio.start();this.night=night;localStorage.setItem('np-night',night);this.elapsed=0;this.outageTimer=0;this.power.reset(night);this.facility.setOutage(false);this.ai.reset(night);this.surveillance.reset();for(const side of['left','right']){this.facility.setDoor(side,false);this.facility.setLight(side,false);this.ui.door(side,false);this.ui.light(side,false)}this.state='playing';this.ui.game(true);this.ui.pause(false);this.ui.show('ending',false);this.ui.jump('',false)}
 title(){this.state='menu';this.ui.game(false);this.ui.pause(false);this.ui.show('ending',false);this.surveillance.open=false;this.ui.tablet(false)}
 pause(force){if(this.state!=='playing'&&this.state!=='paused')return;this.state=force===false?'playing':this.state==='paused'?'playing':'paused';this.ui.pause(this.state==='paused')}
 toggleTablet(){if(this.state!=='playing'||this.power.outage)return;this.surveillance.toggle()}
 toggleDoor(side){if(this.state!=='playing'||this.power.outage)return;const d=this.facility.doors[side];this.facility.setDoor(side,!d.closed);this.ui.door(side,!d.closed);this.audio.door(!d.closed,side)}
 toggleLight(side){if(this.state!=='playing'||this.power.outage)return;const on=!this.facility.lights[side];this.facility.setLight(side,on);this.ui.light(side,on);this.audio.click()}
 controls(dt){if(this.input.pressed('Escape'))this.pause();if(this.state!=='playing')return;if(this.input.pressed('Space'))this.toggleTablet();if(this.input.pressed('KeyQ'))this.toggleDoor('left');if(this.input.pressed('KeyE'))this.toggleDoor('right');if(this.input.pressed('KeyZ'))this.toggleLight('left');if(this.input.pressed('KeyC'))this.toggleLight('right');if(!this.surveillance.open){const target=(this.input.pointerX-.5)*2.2+(this.input.held('KeyA')?-.7:0)+(this.input.held('KeyD')?.7:0);this.yaw=THREE.MathUtils.lerp(this.yaw,target,1-Math.exp(-dt*4))}}
 update(dt,t){this.controls(dt);this.facility.update(dt,t);if(this.state==='playing'){this.elapsed+=dt;const progress=this.elapsed/this.duration;if(progress>=1)return this.win();if(this.power.outage){this.facility.setOutage(true);this.outageTimer+=dt;this.facility.setDoor('left',false);this.facility.setDoor('right',false);this.facility.setLight('left',false);this.facility.setLight('right',false);if(this.surveillance.open)this.surveillance.toggle();if(this.outageTimer>8+Math.random()*8)return this.kill({name:'BLACKOUT ENTITY'})}const p=this.power.update(dt,{tablet:this.surveillance.open,doors:{left:this.facility.doors.left.closed,right:this.facility.doors.right.closed},lights:this.facility.lights});this.ui.update(progress,this.night,p,this.power.usage,this.power.outage);const ctx={time:t,outage:this.power.outage,tablet:this.surveillance.open,camera:this.surveillance.current,usage:this.power.usage,doors:{left:this.facility.doors.left.closed,right:this.facility.doors.right.closed},lights:this.facility.lights,event:(e,a)=>this.event(e,a),kill:a=>this.kill(a),damageCamera:i=>this.surveillance.damage(i)};this.ai.update(dt,ctx)}this.surveillance.update(dt,this.input,this.yaw)}
 event(type,a){if(type==='move'){this.stepTimer++;if(this.stepTimer%2===0)this.audio.step(a)}else if(type==='retreat')this.audio.noise(.25,.08)}
 kill(agent){if(this.state!=='playing')return;this.state='dead';this.audio.alarm();this.ui.jump(agent.name,true);agent.body?.setMode('attack');setTimeout(()=>{this.ui.jump('',false);this.ui.end(false,this.night)},1500)}
 win(){if(this.state!=='playing')return;this.state='won';this.audio.victory();if(this.night<5){localStorage.setItem('np-night',this.night+1)}this.ui.end(true,this.night)}
}