export class Interface{
 constructor(){this.q=s=>document.querySelector(s);this.els={loading:this.q('#loading'),menu:this.q('#menu'),hud:this.q('#hud'),tablet:this.q('#tablet'),pause:this.q('#pause'),ending:this.q('#ending'),doors:this.q('#door-controls'),clock:this.q('#clock'),night:this.q('#night'),battery:this.q('#battery'),fill:this.q('#battery-fill'),draw:this.q('#draw-bars'),warning:this.q('#warning'),camLabel:this.q('#cam-label'),camName:this.q('#cam-name'),offline:this.q('#offline'),map:this.q('#cam-map'),tabletTime:this.q('#tablet-time'),tabletPower:this.q('#tablet-power'),jump:this.q('#jumpscare'),killer:this.q('#killer')};this.nodes=[]}
 show(el,on=true){this.els[el].classList.toggle('hidden',!on)}
 loaded(){setTimeout(()=>this.show('loading',false),450);this.show('menu',true)}
 game(on){this.show('menu',!on);this.show('hud',on);this.show('doors',on)} tablet(on){this.show('tablet',on)} pause(on){this.show('pause',on)}
 buildMap(data,fn){const spots=[[12,14],[82,14],[154,14],[12,62],[154,62],[82,62],[28,112],[140,112]];data.forEach((d,i)=>{const b=document.createElement('button');b.className='cam-node';b.textContent=String(i+1).padStart(2,'0');b.style.left=spots[i][0]+'px';b.style.top=spots[i][1]+'px';b.onclick=()=>fn(i);this.els.map.append(b);this.nodes.push(b)})}
 camera(label,name,offline,index){this.els.camLabel.textContent=label;this.els.camName.textContent=name;this.els.offline.style.display=offline?'grid':'none';this.nodes.forEach((n,i)=>n.classList.toggle('active',i===index))}
 setDamaged(i,on){this.nodes[i]?.classList.toggle('offline',on)}
 update(time,night,power,usage,outage){const hour=Math.min(6,Math.floor(time*6)+12),label=hour>=13?(hour-12)+' AM':hour+' AM';this.els.clock.textContent=label;this.els.night.textContent='NIGHT '+night;this.els.battery.textContent=Math.ceil(power)+'%';this.els.fill.style.width=power+'%';this.els.fill.style.background=power<20?'var(--danger)':power<45?'var(--amber)':'var(--acid)';this.els.draw.innerHTML='';for(let i=0;i<usage;i++){const b=document.createElement('i');if(i>3)b.style.background='var(--danger)';this.els.draw.append(b)}this.els.warning.textContent=outage?'// RESERVE EXHAUSTED //':power<20?'// CRITICAL RESERVE //':'';this.els.tabletTime.textContent=label;this.els.tabletPower.textContent='PWR '+Math.ceil(power)+'%'}
 door(side,on){document.querySelector(`[data-action="${side}-door"]`).classList.toggle('active',on)} light(side,on){document.querySelector(`[data-action="${side}-light"]`).classList.toggle('active',on)}
 end(win,night){this.show('ending',true);this.q('#ending-kicker').textContent=win?'SHIFT COMPLETE':'INCIDENT REPORT';this.q('#ending-title').textContent=win?'6:00 AM':'SIGNAL TERMINATED';this.q('#ending-copy').textContent=win?(night<5?'Site 19 remains operational. The next audit window has been unlocked.':'All five audits complete. Asterion accepts no liability for what you witnessed.'):'Containment failed. Preserve power, study movement patterns, and seal only when a unit reaches the threshold.';this.q('#next-night').style.display=win&&night<5?'block':'none';this.q('#ending-retry').style.display=win?'none':'block'}
 jump(name,on){this.els.killer.textContent=name+' // BREACH';this.show('jump',on)}
}