import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {SSAOPass} from 'three/addons/postprocessing/SSAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
export {THREE};
export class RendererRuntime{
 constructor(canvas){this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.82;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x020405);this.scene.fog=new THREE.FogExp2(0x05090a,.024);this.camera=new THREE.PerspectiveCamera(64,1,.08,110);this.camera.position.set(0,2.4,3.9);this.scene.environment=new THREE.PMREMGenerator(this.renderer).fromScene(new RoomEnvironment(),.04).texture;this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.ssao=new SSAOPass(this.scene,this.camera,innerWidth,innerHeight);this.ssao.kernelRadius=7;this.ssao.minDistance=.003;this.ssao.maxDistance=.13;this.composer.addPass(this.ssao);this.bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.42,.6,.83);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());this.clock=new THREE.Clock();this.callbacks=[];this.running=false;this.resize();addEventListener('resize',()=>this.resize())}
 resize(){const w=innerWidth,h=innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);this.composer.setSize(w,h)}
 add(fn){this.callbacks.push(fn)} start(){if(this.running)return;this.running=true;this.clock.start();const loop=()=>{if(!this.running)return;const dt=Math.min(this.clock.getDelta(),.05),t=this.clock.elapsedTime;for(const fn of this.callbacks)fn(dt,t);this.composer.render();requestAnimationFrame(loop)};requestAnimationFrame(loop)}
}
export class TextureFactory{
 constructor(){this.cache=new Map()}
 make(kind='#4d5550',accent='#1d2523',size=512){const key=kind+accent+size;if(this.cache.has(key))return this.cache.get(key);const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d');x.fillStyle=kind;x.fillRect(0,0,size,size);const img=x.getImageData(0,0,size,size),d=img.data;for(let i=0;i<d.length;i+=4){const n=(Math.random()-.5)*28;d[i]+=n;d[i+1]+=n;d[i+2]+=n}x.putImageData(img,0,0);x.strokeStyle=accent;x.globalAlpha=.35;for(let i=0;i<50;i++){x.lineWidth=Math.random()*2;x.beginPath();x.moveTo(Math.random()*size,Math.random()*size);x.lineTo(Math.random()*size,Math.random()*size);x.stroke()}const color=new THREE.CanvasTexture(c);color.colorSpace=THREE.SRGBColorSpace;color.wrapS=color.wrapT=THREE.RepeatWrapping;const r=document.createElement('canvas');r.width=r.height=size;const rx=r.getContext('2d');const rg=rx.createRadialGradient(size/2,size/2,0,size/2,size/2,size*.7);rg.addColorStop(0,'#a9a9a9');rg.addColorStop(1,'#e1e1e1');rx.fillStyle=rg;rx.fillRect(0,0,size,size);const rough=new THREE.CanvasTexture(r);rough.wrapS=rough.wrapT=THREE.RepeatWrapping;const normal=new THREE.CanvasTexture(c);normal.wrapS=normal.wrapT=THREE.RepeatWrapping;const ao=rough.clone();const metal=rough.clone();const pack={color,rough,normal,ao,metal};this.cache.set(key,pack);return pack}
 material(base,accent,opts={}){const p=this.make(base,accent);return new THREE.MeshStandardMaterial({map:p.color,roughnessMap:p.rough,normalMap:p.normal,aoMap:p.ao,normalScale:new THREE.Vector2(.08,.08),roughness:opts.roughness??.72,metalness:opts.metalness??.15,metalnessMap:p.metal,color:0xffffff,emissive:opts.emissive??0x000000,emissiveIntensity:opts.emissiveIntensity??0})}
}
export const ease=(a,b,s)=>THREE.MathUtils.lerp(a,b,1-Math.exp(-s));
export const box=(w,h,d,mat)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.castShadow=m.receiveShadow=true;return m};
export const cylinder=(r,h,mat,seg=16)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),mat);m.castShadow=m.receiveShadow=true;return m};